    apiVersion: v1
    kind: Service
    metadata:
      name: nginx-service
    spec:
      selector:
        app: my-app-1
      ports:
        - protocol: TCP
          port: 80
          targetPort: 80
      type: LoadBalancer